### PR TITLE
dont polyfill ObsoletedOSPlatformAttribute on net5 and net6

### LINKED ISSUE #355: `OSPlatformAttribute` generates CS0436 with NET5
#### Describe the bug

This is a really minor thing, as I only found it while scrutinizing this repo.

`OSPlatformAttribute` is polyfilled for NET5, but it's already included in NET5.
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.osplatformattribute?view=net-5.0

https://github.com/SimonCropp/Polyfill/blob/b3d94560739e923662ea3cccdfb3120f389f810d/src/Polyfill/PlatformCompatibility/OSPlatformAttribute.cs#L4

#### Minimal Repro

For a NET5.0 project consuming PolyFill:
```cs
using System.Runtime.Versioning;

class MyAttribute(string platformName) : OSPlatformAttribute(platformName);
```

Generates the following compiler warning

```
The type 'OSPlatformAttribute' in 'C:\Users\jn\.nuget\packages\polyfill\8.0.0-beta.4\contentFiles\cs\netstandard2.0\Polyfill\PlatformCompatibility\OSPlatformAttribute.cs' conflicts with the imported type 'OSPlatformAttribute' in 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Using the type defined in 'C:\Users\jn\.nuget\packages\polyfill\8.0.0-beta.4\contentFiles\cs\netstandard2.0\Polyfill\PlatformCompatibility\OSPlatformAttribute.cs'.
```

#### Submit a PR that fixes the bug

I don't have a pretty way to solve this.
My currently best guess is to:
* Avoid polyfilling `OSPlatformAttribute` for NET5
* For each polyfilled child class of `OSPlatformAttribute` use reflection to set `OSPlatformAttribute.PlatformName`

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #355

### CODE REVIEW

File: src/Polyfill/PlatformCompatibility/ObsoletedOSPlatformAttribute.cs [hunk 1]
```diff
@@ -1,6 +1,8 @@
 ﻿// <auto-generated />
 #pragma warning disable
 
+#if !NET6_0 && !NET5_0
+
 #if !NET7_0_OR_GREATER
```
Comment (dahlbyk) [inline src/Polyfill/PlatformCompatibility/ObsoletedOSPlatformAttribute.cs:6]: Am I missing how this is logically different from `#if !NET5_0_OR_GREATER`?
